### ISSUE TITLE
Upload the Docker image in build-fastapi to ghcr.io.

### ISSUE THREAD

**Issue by FabianSchurig** [FabianSchurig/promptflow-starter-template#1]
**Title:** Modify `build-fastapi` Workflow to Push Docker Image to GitHub Container Registry

**Description:**

The current GitHub Actions workflow in `.github/workflows/build.yml` defines two jobs: `build-package` and `build-fastapi`. While both jobs build Docker images, only the `build-package` job is configured to push its Docker image to GitHub Container Registry (ghcr.io). The `build-fastapi` job builds the Docker image for the FastAPI application but does not push it to ghcr.io, leaving the image inaccessible for deployments that rely on the container registry.

**Issue Details:**

- **Job Affected:** `build-fastapi`
- **File:** `.github/workflows/build.yml`
- **Current Configuration:**
  - The `build-fastapi` job has `push: false` in the Docker build step, which prevents the image from being pushed to ghcr.io.
  
**Proposed Solution:**

Modify the `build-fastapi` job to enable pushing the built Docker image to ghcr.io by setting `push: true`. This change will ensure that the Docker image is available in the container registry for deployment and other uses.

**Detailed Steps to Resolve:**

1. **Update the `build-fastapi` Job:**

   Change the `push` parameter from `false` to `true` in the `docker/build-push-action@v3` step.

   ```yaml
   build-fastapi:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout repository
         uses: actions/checkout@v2

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2

       - name: Set repository name to lowercase
         run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

       - name: Log in to GitHub Container Registry
         uses: docker/login-action@v2
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}

       - name: Build and push Docker image
         uses: docker/build-push-action@v3
         with:
           context: .
           push: true  # Changed from false to true
           tags: |
             ghcr.io/${{ env.REPO_NAME }}/fastapi:latest
             ghcr.io/${{ env.REPO_NAME }}/fastapi:${{ github.sha }}
           file: Dockerfile.fastapi
           build-args: |
             REPO_URL=${{ secrets.PYPI_REPOSITORY_URL }}
             REPO_USERNAME=${{ secrets.PYPI_USERNAME }}
             REPO_PASSWORD=${{ secrets.PYPI_PASSWORD }}
             PACKAGE_INSTALL_NAME=${{ github.event.repository.name }}
             PACKAGE_IMPORT_NAME=$(echo ${{ github.event.repository.name }} | tr '-' '_')
           target: package-installer
   ```

2. **Verify GitHub Container Registry Permissions:**

   Ensure that the `GITHUB_TOKEN` or any personal access token used has the necessary permissions to push images to ghcr.io. The token should have at least the `write:packages` and `read:packages` scopes.

3. **Test the Workflow:**

   - Commit the updated workflow file.
   - Trigger the workflow by pushing to the `main` branch.
   - Confirm that the `build-fastapi` job successfully pushes the Docker image to ghcr.io.

**Benefits of the Change:**

- **Deployment Automation:** Pushing the Docker image to ghcr.io allows for seamless deployment processes that can pull the latest image directly from the registry.
- **Versioning and Traceability:** By tagging images with `latest` and `${{ github.sha }}`, you maintain a clear history of builds corresponding to specific commits.
- **Collaborative Access:** Team members can access and use the Docker images from a centralized registry.

**Additional Recommendations:**

- **Error Handling:** Implement error notifications in the workflow to alert the team if a push to ghcr.io fails.
- **Security Best Practices:**
  - Regularly rotate secrets and tokens used in the workflow.
  - Ensure that repository secrets (like `PYPI_REPOSITORY_URL`, `PYPI_USERNAME`, `PYPI_PASSWORD`, `PYPI_API_TOKEN`) are securely stored and have the minimum necessary permissions.
- **Documentation:**
  - Update the project README to include information about the Docker images and how they can be accessed from ghcr.io.
  - Document the workflow steps for future reference and onboarding.

**Alternative Considerations:**

- **Automated Testing:** Before pushing the Docker image, consider adding steps to run automated tests on the FastAPI application to ensure stability and reliability.
- **Multi-Platform Builds:** If there's a need to support multiple architectures (e.g., amd64, arm64), configure the `docker/setup-buildx-action` and `docker/build-push-action` to build and push multi-platform images.

**Background Information:**

The GitHub Actions workflows are pivotal for Continuous Integration and Continuous Deployment (CI/CD). By automating the build and push process for Docker images, we enhance efficiency and reduce the potential for human error. Ensuring that both `build-package` and `build-fastapi` jobs push their respective images to ghcr.io keeps the development and deployment pipelines consistent.

**Next Steps:**

- Assign this issue to a team member for implementation.
- Schedule a review of the updated workflow after implementation to confirm functionality.
- Monitor the first few workflow runs to ensure the images are correctly pushed and accessible.
